assistant/urls.py
from django.urls import path

from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'assistant'
urlpatterns = [
   # ex: /assistant/
    path('', views.index, name='index'),
    # ex: /assistant/5/
    # path('<int:question_id>/', views.detail, name='detail'),
    # # ex: /assistant/5/results/
    # path('<int:question_id>/results/', views.results, name='results'),
    # # ex: /assistant/5/vote/
    # path('<int:question_id>/vote/', views.vote, name='vote'),
    path('add',views.add_person, name='add_person'),
    path('recognize',views.recognize, name='recognize'),
    path('chat',views.chat, name='chat'),
    path('ocr',views.ocr, name='ocr'),
]

athena/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('assistant/', include('assistant.urls'))
]

assistant/models.py
from django.db import models

# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

assistant/views.py
from .models import Question,Choice
from django.http import JsonResponse
from django.template import loader
from django.http import HttpResponse, HttpResponseRedirect , Http404
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.conf import settings
from django.core.files.storage import FileSystemStorage
from django.views.decorators.csrf import csrf_exempt
import os, sys
from os import listdir
from os.path import isfile, join,split
from .modules.FaceRecognizer import FaceRecognizer
from .modules.Chatbot import Chatbot
from .modules.TextRecognizer import TextRecognizer
import json
import urllib.request
import shutil
from urllib.parse import urlparse
# from django.core.cache import cache
# import _pickle as cPickle


# Create your views here.

def index(request):
    return HttpResponse("Hello, world. My name is Athena.")
    
@csrf_exempt
def add_person(request):
    if request.method == 'POST' and 'imgUrl' in request.POST and 'name' in request.POST and 'auth' in request.POST and request.POST['auth'] == 'GxsQXvHY5XMo@4%':
        imgUrl = request.POST['imgUrl']
        urlParser =  urlparse(imgUrl)
        fileName = os.path.basename(urlParser.path)
        name = request.POST['name']

        # if(not os.path.isdir(os.path.join(settings.BASE_DIR, 'media/'+name))):
        #     os.mkdir(os.path.join(settings.BASE_DIR, 'media/'+name), 755)       
        # fs = FileSystemStorage(location='media/'+name)
        # fs = FileSystemStorage(location='media/dataset')

        #get the path of all the files in the folder
        imagePaths = [join(settings.BASE_DIR+'/media/dataset',f) for f in listdir(settings.BASE_DIR+'/media/dataset')]

        #create empty Persons list
        Persons = {}
        #create empty serials list
        serials = {}
        #now looping through all the image paths and loading the Ids and the images
        for imagePath in imagePaths:
            #get the Id from the image
            Id = int(split(imagePath)[-1].split(".")[1])
            nameOfPerson = split(imagePath)[-1].split(".")[0]
            #get the name from the image
            Persons[nameOfPerson] = Id
            #get serial number
            serial = int(split(imagePath)[-1].split(".")[2])         
            serials[nameOfPerson] = max(1, serials.get(nameOfPerson,1) ,serial) 
        if name not in Persons.keys():
            maxId = max(Persons.values()) if Persons else 0
            imgName = name+'.'+str(maxId+1)+'.1.'+split(fileName)[-1].split(".")[1]
        else:            
            imgName = name+'.'+str(Persons[name])+'.'+str(serials[name]+1)+'.'+split(fileName)[-1].split(".")[1]

        # Download the file from `url` and save it locally under `file_name`:
        with urllib.request.urlopen(imgUrl) as response, open(settings.BASE_DIR+'/media/dataset/'+imgName, 'wb+') as out_file:
            shutil.copyfileobj(response, out_file)

        # filename = fs.save(imgName, myfile)
        uploaded_file_url = settings.BASE_DIR+'/media/dataset/'+imgName

        # train our model
        faceRecognizer = FaceRecognizer(settings.BASE_DIR+'/assistant/modules')
        faceRecognizer.train_and_save(settings.BASE_DIR+'/media/dataset')

        # return render(request, 'assistant/add_person.html', {
        #     'uploaded_file_url': uploaded_file_url,
        #     'name' : name
        # })
        return JsonResponse({'uploaded_file_url': uploaded_file_url , 'name' : name ,'status' : 'success'})
    # return render(request, 'assistant/add_person.html')
    else:
        return JsonResponse({'Error': "Please specify a name and the url of image and enter your auth key" ,'status' : 'fail'})

@csrf_exempt
def recognize(request):
    if request.method == 'POST' and 'imgUrl' in request.POST and 'auth' in request.POST and request.POST['auth'] == 'GxsQXvHY5XMo@4%':
        imgUrl = request.POST['imgUrl']
        urlParser =  urlparse(imgUrl)
        fileName = os.path.basename(urlParser.path)

        # Download the file from `url` and save it locally under `file_name`:
        with urllib.request.urlopen(imgUrl) as response, open(settings.BASE_DIR+'/media/uploads/'+fileName, 'wb+') as out_file:
            shutil.copyfileobj(response, out_file)

        # fs = FileSystemStorage(location='media/uploads')
        # filename = fs.save(myfile.name, myfile)
        uploaded_file_url = settings.BASE_DIR+'/media/uploads/'+fileName

        # recognize the image
        faceRecognizer = FaceRecognizer(settings.BASE_DIR+'/assistant/modules')
        faces = faceRecognizer.recognize_faces(join(settings.BASE_DIR+'/media/uploads',fileName),settings.BASE_DIR+'/media/dataset')

        # convert into JSON:
        faces = json.dumps(faces)
 
        # return render(request, 'assistant/recognize_person.html', {
        #     'uploaded_file_url': uploaded_file_url,
        #     'faces' : faces
        # })
        return JsonResponse({'uploaded_file_url': uploaded_file_url , 'faces' : faces ,'status' : 'success'})    
    # return render(request, 'assistant/recognize_person.html')
    else:
        return JsonResponse({'Error': "Please specify the Url of image and your auth key" ,'status' : 'fail'})


@csrf_exempt
def chat(request):
    if request.method == 'POST' and 'msg' in request.POST and 'auth' in request.POST and request.POST['auth'] == 'GxsQXvHY5XMo@4%':
        user_msg = request.POST['msg']   
        # # this key is used to `set` and `get` 
        # # your trained model from the cache
        # model_cache_key = 'model_cache' 

        # # get model from cache        
        # model = cache.get(model_cache_key) 

        # if model is None:
        #     # your model isn't in the cache
        #     # so `set` it

        #     # load model
        #     f = open(settings.BASE_DIR+'/assistant/modules/classifier.pickle', 'rb')  
        #     model = cPickle.load(f)
        #     f.close()
            
        #     # save in the cache
        #     # None is the timeout parameter. It means cache forever
        #     cache.set(model_cache_key, model, None)        
        chatbot = Chatbot(settings.BASE_DIR+'/assistant/modules')
        reply , sentiment = chatbot.generate_reply(user_msg)
        return JsonResponse({'Reply': reply , 'sentiment' : sentiment ,'status' : 'success'})        
    else:
        return JsonResponse({'Error': "Please specify the msg of user and your auth key" ,'status' : 'fail'})

@csrf_exempt
def ocr(request):
    if request.method == 'POST' and 'img' in request.POST and 'lang' in request.POST and 'auth' in request.POST and request.POST['auth'] == 'GxsQXvHY5XMo@4%':
        img_url = request.POST['img']
        lang = request.POST['lang']
        urlParser =  urlparse(img_url)
        fileName = os.path.basename(urlParser.path)

        # Download the file from `url` and save it locally under `file_name`:
        with urllib.request.urlopen(img_url) as response, open(settings.BASE_DIR+'/media/uploads/'+fileName, 'wb+') as out_file:
            shutil.copyfileobj(response, out_file)

        recognizer = TextRecognizer(settings.BASE_DIR+'/assistant/modules')

        results = recognizer.recognize(settings.BASE_DIR+'/media/uploads/'+fileName,lang = lang)        
        # loop over the results
        texts = []       
        for ((startX, startY, endX, endY), text) in results:
                texts.append(text)
        return JsonResponse({'Text': texts ,'status' : 'success'})        
    else:
        return JsonResponse({'Error': "Please specify the img_url of the image with the , lang parameter and your auth key" ,'status' : 'fail'})
    pass

assistant/templates/assistant/add_person.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Upload a new person's image</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- <link rel="stylesheet" type="text/css" media="screen" href="main.css">
    <script src="main.js"></script> -->
</head>

<body>
    <form method="post" action="{% url 'assistant:add_person' %}" enctype="multipart/form-data">
        <!-- {% csrf_token %} -->
        <label for="name"> Person name :</label>
        <input type="text" name="name">
        </br>
        <label for="myfile"> Image :</label>
        <input type="file" name="myfile">
        </br>
        <button type="submit">Upload</button>
    </form>

    {% if uploaded_file_url %}
    <p>Image uploaded at: <a href="{{ uploaded_file_url }}">{{ uploaded_file_url }}</a></p>
    <p>Person name: {{ name }}</p>
    {% endif %}
</body>

</html>

assistant/templates/assistant/detail.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Question</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- <link rel="stylesheet" type="text/css" media="screen" href="main.css">
    <script src="main.js"></script> -->
</head>

<body>
    <!-- <h1>{{ question.question_text }}</h1>
    <ul>
    {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }}</li>
    {% endfor %}
    </ul> -->
    <h1>{{ question.question_text }}</h1>

    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    <form action="{% url 'assistant:vote' question.id %}" method="post">
        {% csrf_token %}
        {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {% endfor %}
        <input type="submit" value="Vote">
    </form>
</body>

</html>>

assistant/templates/assistant/index.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Test page</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- <link rel="stylesheet" type="text/css" media="screen" href="main.css">
    <script src="main.js"></script> -->
</head>
<body>
    {% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'assistant:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}
</body>
</html>

assistant/templates/assistant/recognize_person.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Upload an image to be recognized</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- <link rel="stylesheet" type="text/css" media="screen" href="main.css">
    <script src="main.js"></script> -->
</head>

<body>
    <form method="post" action="{% url 'assistant:recognize' %}" enctype="multipart/form-data">
        <!-- {% csrf_token %} -->
        <label for="myfile"> Image :</label>
        <input type="file" name="myfile">
        </br>
        <button type="submit">Upload</button>
    </form>

    {% if uploaded_file_url %}
    <p>Image uploaded at: <a href="{{ uploaded_file_url }}">{{ uploaded_file_url }}</a></p>
    <p>Recognition results: </p>
    <ul>
        <!-- {% for face in faces %}
        <li>Image {{ face }}</li>
        {% endfor %} -->
        {{ faces }}
    </ul>
    {% endif %}
</body>

</html>

assistant/templates/assistant/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'assistant:detail' question.id %}">Vote again?</a>